projeto/apostas/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, PasswordField, SubmitField, BooleanField, IntegerField, SelectField
from wtforms.validators import DataRequired, Length, EqualTo, NumberRange, Email, ValidationError
from projeto.models import User 

class nova_Aposta(FlaskForm):
    desporto = SelectField('Desporto', choices=[('Tenis','Tenis'),('Futebol','Futebol')], validators=[DataRequired()])
    moeda = SelectField('Moeda',choices=[('€','Euro'),('£','Libra'),('$','Dollar'),('C','Cardan')],validators=[DataRequired()])
    valor = IntegerField('Valor', validators=[DataRequired(), NumberRange(min=0)])
    evento = SelectField('Evento', choices=[], validators = [DataRequired()])

    submit = SubmitField('Fazer Aposta')

class cambio_moedas(FlaskForm):
    moeda = SelectField('Moeda',choices=[('€','Euro'),('£','Libra'),('$','Dollar'),('C','Cardan')],validators=[DataRequired()])
    moeda2 = SelectField('Moeda2', choices=[('€','Euro'),('£','Libra'),('$','Dollar'),('C','Cardan')],validators=[DataRequired()])
    valor = IntegerField('Valor', validators=[DataRequired(), NumberRange(min=0)])

    submit = SubmitField('Cambiar')

projeto/apostas/routes.py
from flask import Blueprint
import os
import secrets
from datetime import datetime
from PIL import Image #dá resize nos icons para nao ocupar muito espaço
from flask import render_template, url_for, flash, redirect, request, jsonify, abort
from projeto import app, db, bcrypt
from projeto.apostas.forms import nova_Aposta, cambio_moedas
from projeto.models import User, Aposta, Evento, Taxa
from flask_login import login_user, current_user, logout_user, login_required
import json

apostas = Blueprint('apostas',__name__)

@apostas.route("/aposta/nova", methods=['GET', 'POST'])
@login_required
def novaAposta():
    atualizaApostas()
    form = nova_Aposta()
    req = request.form
    valor = req.get('valor')
    moeda = req.get('moeda')

    if form.moeda.data == '€':
        if current_user.saldoEuro < int(0 if valor is None else valor):
            flash('Não tem saldo suficiente!','danger')
            return render_template('novaAposta.html', title='Nova Aposta', form=form)

    if form.moeda.data == '$':
        if current_user.saldoDollar < int(0 if valor is None else valor):
            flash('Não tem saldo suficiente!','danger')
            return render_template('novaAposta.html', title='Nova Aposta', form=form)

    if form.moeda.data == '£':
        if current_user.saldoLibra < int(0 if valor is None else valor):
            flash('Não tem saldo suficiente!','danger')
            return render_template('novaAposta.html', title='Nova Aposta', form=form)

    if form.moeda.data == 'C':
        if current_user.saldoCardan < int(0 if valor is None else valor):
            flash('Não tem saldo suficiente!','danger')
            return render_template('novaAposta.html', title='Nova Aposta', form=form)
    
    
    form.evento.choices = [(evento.id, 'Jogo:' + str(evento.liga) + '\n Equipa:' + str(evento.equipa) + '\n Odd:' + str(evento.odd)) for evento in Evento.query.filter_by(desporto='Tenis').all()]

    if request.method == 'POST':
        evento = Evento.query.filter_by(id=form.evento.data).first()
        useratS = User.query.filter_by(id=current_user.id).first()
        if form.moeda.data == '€':
            current_user.saldoEuro = (useratS.saldoEuro - int(form.valor.data))
        if form.moeda.data == '£':
            current_user.saldoLibra = (useratS.saldoLibra - int(form.valor.data))
        if form.moeda.data == '$':
            current_user.saldoDollar = (useratS.saldoDollar - int(form.valor.data))
        if form.moeda.data == 'C':
            current_user.saldoCardan = (useratS.saldoCardan - int(form.valor.data))
        nova = Aposta(desporto=form.desporto.data, dia=evento.dia, mes=evento.mes,ano=evento.ano,hora=evento.hora,minuto=evento.minuto,evento=evento.liga, estado="Aberto",equipa=evento.equipa,valor=form.valor.data,moeda=form.moeda.data,odd=evento.odd,potencial=evento.potencial,user_id=current_user.id)
        db.session.add(nova)
        db.session.commit()
        flash('Aposta efetuada com sucesso!','success')
        return redirect(url_for('main.home'))
    
    return render_template('novaAposta.html', title='Nova Aposta', form=form)

@apostas.route("/aposta/<desporto>", methods=['GET', 'POST'])
@login_required 
def evento(desporto):
    eventos = Evento.query.filter_by(desporto=desporto).all()
    eventoARR = []
    for evento in eventos:
        eventoObj={}
        eventoObj['id'] = evento.id
        eventoObj['jornada'] = evento.jornada
        eventoObj['liga'] = evento.liga
        eventoObj['equipa'] = evento.equipa
        eventoObj['odd'] = evento.odd
        eventoARR.append(eventoObj)

    return jsonify({'eventos' : eventoARR })


def atualizaApostas():
    currentDay = datetime.now().day
    currentMonth = datetime.now().month
    currentYear = datetime.now().year
    currentHour = datetime.now().hour
    currentMinute = datetime.now().minute

    aposta = Aposta.query.filter_by(user_id=current_user.id).all()
    for p in aposta:
        if p.estado == 'Aberto':
            if p.ano <= currentYear:
                if p.mes <= currentMonth:
                    if p.dia < currentDay:
                        flash('Houve atualização de apostas','success')
                        p.estado = 'Fechado'
                        atualizaSaldo(p)
                    if p.dia == currentDay:
                        if p.hora < currentHour:
                            flash('Houve atualização de apostas, Jogo de {p.equipa} terminou!','success')
                            p.estado = 'Fechado'
                            atualizaSaldo(p)
                        if p.hora == currentHour:
                            if currentMinute > p.minuto:
                                flash('Houve atualização de apostas','success')
                                p.estado = 'Fechado'
                                atualizaSaldo(p)
    db.session.commit()
                    
def atualizaSaldo(p):         
    if(p.potencial=='G'):
        if (p.moeda == '€'):
            usernow = User.query.filter_by(username=current_user.username).first()
            current_user.saldoEuro += (p.valor * p.odd)
        if (p.moeda == '$'):
            usernow = User.query.filter_by(username=current_user.username).first()
            current_user.saldoDollar += (p.valor * p.odd)
        if (p.moeda == '£'):
            usernow = User.query.filter_by(username=current_user.username).first()
            current_user.saldoLibra += (p.valor * p.odd)
        if (p.moeda == 'C'):
            usernow = User.query.filter_by(username=current_user.username).first()
            current_user.saldoCardan += (p.valor * p.odd)
    #else:
    #    if(p.moeda == '€'):
    #        usernow = User.query.filter_by(username=current_user.username).first()
    #        current_user.saldoEuro -= (p.valor * p.odd)
    #    if(p.moeda == '$'):
    #        usernow = User.query.filter_by(username=current_user.username).first()
    #        current_user.saldoDollar -= (p.valor * p.odd)
    #    if(p.moeda == '£'):
    #        usernow = User.query.filter_by(username=current_user.username).first()
    #        current_user.saldoLibra -= (p.valor * p.odd)
    #    if(p.moeda == 'C'):
    #        usernow = User.query.filter_by(username=current_user.username).first()
    #        current_user.saldoCardan -= (p.valor * p.odd)   

    db.session.commit()


@apostas.route("/cambio", methods=['GET', 'POST'])
@login_required 
def cambio():
    atualizaApostas()

    form = cambio_moedas()
    req = request.form
    valor = req.get('valor')

    if form.validate_on_submit():
        if form.moeda.data == '€' and form.moeda2.data == '€':
            flash('Não é possível fazer o câmbio entre moedas iguais','danger')
        if form.moeda.data == 'C' and form.moeda2.data == 'C':
            flash('Não é possível fazer o câmbio entre moedas iguais','danger')
        if form.moeda.data == '£' and form.moeda2.data == '£':
            flash('Não é possível fazer o câmbio entre moedas iguais','danger')
        if form.moeda.data == '$' and form.moeda2.data == '$':
            flash('Não é possível fazer o câmbio entre moedas iguais','danger')


        if form.moeda.data == '€' and form.moeda2.data == 'C':
            if current_user.saldoEuro < form.valor.data:
                flash('Não tem saldo suficiente','danger')
            else: 
                tax = Taxa.query.filter_by(id=1).first()
                current_user.saldoEuro -= int(valor)
                current_user.saldoCardan += int(valor)*float(tax.taxas)
                flash('Câmbio realizado com sucesso','success')

        if form.moeda.data == '€' and form.moeda2.data == '£':
            if current_user.saldoEuro < form.valor.data:
                flash('Não tem saldo suficiente','danger')
            else: 
                tax = Taxa.query.filter_by(id=3).first()
                current_user.saldoEuro -= int(valor)
                current_user.saldoLibra += int(valor)*float(tax.taxas)
                flash('Câmbio realizado com sucesso','success')
        if form.moeda.data == '€' and form.moeda2.data == '$':
            if current_user.saldoEuro < form.valor.data:
                flash('Não tem saldo suficiente','danger')
            else: 
                tax = Taxa.query.filter_by(id=2).first()
                current_user.saldoEuro -= int(valor)
                current_user.saldoDollar += int(valor)*float(tax.taxas)
                flash('Câmbio realizado com sucesso','success')
        if form.moeda.data == 'C' and form.moeda2.data == '$':
            if current_user.saldoCardan < form.valor.data:
                flash('Não tem saldo suficiente','danger')
            else: 
                tax = Taxa.query.filter_by(id=4).first()
                current_user.saldoCardan -= int(valor)
                current_user.saldoDollar += int(valor)*float(tax.taxas)
                flash('Câmbio realizado com sucesso','success')

        if form.moeda.data == 'C' and form.moeda2.data == '£':
            if current_user.saldoCardan < form.valor.data:
                flash('Não tem saldo suficiente','danger')
            else: 
                tax = Taxa.query.filter_by(id=5).first()
                current_user.saldoCardan -= int(valor)
                current_user.saldoLibra += int(valor)*float(tax.taxas)
                flash('Câmbio realizado com sucesso','success')

        if form.moeda.data == 'C' and form.moeda2.data == '€':
            if current_user.saldoCardan < form.valor.data:
                flash('Não tem saldo suficiente','danger')
            else: 
                tax = Taxa.query.filter_by(id=6).first()
                current_user.saldoCardan -= int(valor)
                current_user.saldoEuro += int(valor)*float(tax.taxas)
                flash('Câmbio realizado com sucesso','success')
        
        if form.moeda.data == '£' and form.moeda2.data == '€':
            if current_user.saldoLibra < form.valor.data:

projeto/main/routes.py
from flask import Blueprint
import os
import secrets
from datetime import datetime
from PIL import Image #dá resize nos icons para nao ocupar muito espaço
from flask import render_template, url_for, flash, redirect, request, jsonify, abort
from projeto import app, db, bcrypt
from projeto.models import User, Aposta, Evento, Taxa
from flask_login import login_user, current_user, logout_user, login_required
import json

main = Blueprint('main',__name__)


data = json.load(open("C:/Users/beatr/Desktop/RASCodigo/Api.json"))
camb = json.load(open("C:/Users/beatr/Desktop/RASCodigo/Cambio.json"))

def loadEventos():
    t = True
    x = True
    for evento in data['Eventos']:
        ev = Evento.query.filter_by(id=evento['id']).first()
       
        if ev and t:
            t = False
            flash('Eventos desportivos up to date!', 'success')
        if not ev:
            novo = Evento(id=evento['id'], desporto=evento['Desporto'], equipa=evento['Atleta'], liga=evento['Liga'],jornada=evento['Jornada'], odd=evento['Odd'], dia=evento['Dia'], mes=evento['Mes'],ano=evento['Ano'],hora=evento['Hora'],minuto=evento['Minuto'],potencial=evento['Potencial'])
            db.session.add(novo)
            db.session.commit()
            if x:
                flash('Novos eventos desportivos disponíveis!', 'success')
                x = False


def loadTaxa():
    t = True
    for taxas in camb['Taxas']:
        cb = Taxa.query.filter_by(id=taxas['id']).first()

        if not cb :
            taxa = Taxa(id=taxas['id'], moeda = taxas['Moeda'], moeda2 = taxas['Moeda2'], taxas = float(taxas['taxa']))
            db.session.add(taxa)
            flash('Taxas diárias de câmbio atualizadas','success')

        if cb and cb.taxas != taxas['taxa']:
            cb.taxas = float(taxas['taxa'])
            if t:
                flash('Taxas diárias de câmbio atualizadas','success')
                t=False

        if cb and cb.taxas == taxas['taxa']:
            if t:
                flash('Taxas diárias prontas','success')
                t=False

        db.session.commit()



@main.route("/")
@main.route("/home")
def home():
    #usa template
    loadEventos()
    loadTaxa()
    return render_template('home.html', data=data)

@main.route("/about")
def about():
    return render_template('about.html', title='Sobre a Aplicação')

projeto/templates/Apostas.html
{% extends "layout.html" %}
{% block content %}
 <h1 class="mb-3"> Apostas de {{user.username}} ({{apostas.total}})</h1>
    {% for aposta in apostas.items %}
        <article class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
              {{ aposta.user_id.username }}</a>
              <small class="text-muted">Valor apostado:{{ aposta.valor }} {{aposta.moeda}}</small>
            </div>
            <p class="article-content">Estado Atual: <p style="color:#008000">{{ aposta.estado}}</p></p>
            <p class="article-content">Evento Desportivo:{{ aposta.evento }}</p>
            <p class="article-content">Equipa:{{ aposta.equipa}}</p>
            <p class="article-content">Odd:{{ aposta.odd}}</p>
            <p class="article-content"> Data do Jogo: {{ aposta.dia }}/{{aposta.mes}}/{{aposta.ano}}</p>
            <p class="article-content"> Hora do Jogo: {{ aposta.hora }}:{{aposta.minuto}}</p>
          </div >
        </article>
    {% endfor %}
{% endblock content %}

projeto/templates/about.html
{% extends "layout.html" %}
{% block content%}
    <h1>Sobre a Aplicação</h1>
{% endblock %}

projeto/templates/cambio.html
{% extends "layout.html" %}
{% block content%}
<div class="content-section">
    <form method="POST" action="">
        <div class="content-section">
            <form method="POST" action="">
                {{form.hidden_tag()}}
                <fieldset class="form-group">
                    <legend class=border-bottom mb-4">Câmbio</legend>
                    <div class="form-group">
                        {{form.moeda.label(class="form-control-label")}}
                        {{form.moeda(class="form-control form-control-lg") }}
                    </div>
                    <div class="form-group">
                        {{form.moeda2.label(class="form-control-label")}}
                        {{form.moeda2(class="form-control form-control-lg") }}
                    </div>
                    <div class="form-group">
                        {{form.valor.label(class="form-control-label")}}
                        {{form.valor(class="form-control form-control-lg") }}
                    </div>
                    <div class="form-group">
                        {{ form.submit(class="btn btn-outline-info") }}
                    </div>
    </form>
{% endblock %}

projeto/templates/cashout.html
{% extends "layout.html" %}
{% block content%}
<div class="content-section">
    <form method="POST" action="">
        <div class="content-section">
            <form method="POST" action="">
                {{form.hidden_tag()}}
                <fieldset class="form-group">
                    <legend class=border-bottom mb-4">CashOut</legend>
                    <div class="form-group">
                        {{form.moeda.label(class="form-control-label")}}
                        {{form.moeda(class="form-control form-control-lg") }}
                    </div>
                    <div class="form-group">
                        {{form.valor.label(class="form-control-label")}}
                        {{form.valor(class="form-control form-control-lg") }}
                    </div>
                    <div class="form-group">
                        {{ form.submit(class="btn btn-outline-info") }}
                    </div>
    </form>
{% endblock %}

projeto/templates/conta.html
{% extends "layout.html" %}
{% block content%}
    <div class="content-section">
        <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
            <h2 class="account-heading">{{current_user.username}}</h2>
            <h2 class="account-heading">{{current_user.status}}</h2>
            <p class="text-secondary">{{current_user.email}}</p>
            <p class="text-secondary">Saldo €: {{current_user.saldoEuro}}</p>
            <p class="text-secondary">Saldo $: {{current_user.saldoDollar}}</p>
            <p class="text-secondary">Saldo £: {{current_user.saldoLibra}}</p>
            <p class="text-secondary">Saldo C: {{current_user.saldoCardan}}</p>
        </div>
        </div>
        <!-- FORM HERE -->
        <div class="content-section">
            <form method="POST" action="" enctype="multipart/form-data">
                {{form.hidden_tag()}}
                <fieldset class="form-group">
                    <legend class=border-bottom mb-4">Atualize os dados da sua conta:</legend>
                    <div class="form-group">
                        {{form.username.label(class="form-control-label")}}

                        {% if form.username.errors %}
                            {{ form.username(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.username.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.username(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{form.email.label(class="form-control-label")}}
                        {% if form.email.errors %}
                            {{ form.email(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.email(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{form.DepositoEuro.label(class="form-control-label")}}
                        {% if form.DepositoEuro.errors %}
                            {{ form.DepositoEuro(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.DepositoEuro.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.DepositoEuro(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{form.DepositoDollar.label(class="form-control-label")}}
                        {% if form.DepositoDollar.errors %}
                            {{ form.DepositoDollar(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.DepositoDollar.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.DepositoDollar(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{form.DepositoLibra.label(class="form-control-label")}}
                        {% if form.DepositoLibra.errors %}
                            {{ form.DepositoLibra(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.DepositoLibra.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.DepositoLibra(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{form.DepositoCardan.label(class="form-control-label")}}
                        {% if form.DepositoCardan.errors %}
                            {{ form.DepositoCardan(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.DepositoCardan.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.DepositoCardan(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{form.foto.label()}}
                        {{form.foto(class="form-control-file")}}
                        {% if form.foto.errors%}
                            {% for error in form.foto.errors %}
                                <span class="text-danger">{{ error }}</span></br>
                            {% endfor %}
                        {% endif %}
                    </div>
                </fieldset>
                <div class="form-group">
                    {{ form.submit(class="btn btn-outline-info") }}
                </div>
            </form>
        </div>
    </div>
{% endblock %}

projeto/templates/home.html
{% extends "layout.html" %}
{% block content%}
    <h1>RASBet</h1>
{% endblock %}

projeto/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- para aplicar a main.css -->
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='main.css')}}">

    {% if title %}
        <title> Apostas Desportivas - {{title}}</title>
    {% else %}
        <title>Apostas Desportivas</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">RASBet</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{url_for('main.home') }}">Home</a>
              <a class="nav-item nav-link" href="{{url_for('main.about') }}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated and current_user.estado == 1 %}
                <a class="nav-item nav-link" href="{{url_for('apostas.cambio') }}">Cambio</a>
                <a class="nav-item nav-link" href="{{url_for('users.cashout') }}">Cash Out</a>
                <a class="nav-item nav-link" href="{{url_for('users.myapostas') }}">As minhas Apostas</a>
                <a class="nav-item nav-link" href="{{url_for('apostas.novaAposta') }}">Nova Aposta</a>
                <a class="nav-item nav-link" href="{{url_for('users.conta') }}">A minha conta</a>
                <a class="nav-item nav-link" href="{{url_for('users.logout') }}">Logout</a>
                {% endif %}
              {% if not current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{url_for('users.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{url_for('users.registo') }}">Registo</a>
              {% endif %}
              {% if current_user.is_authenticated and current_user.estado == 2 %}
                <a class="nav-item nav-link" href="{{url_for('apostas.cambio') }}">Cambio</a>
                <a class="nav-item nav-link" href="{{url_for('users.quest') }}">Questionário</a>
                <a class="nav-item nav-link" href="{{url_for('users.cashout') }}">Cash Out</a>
                <a class="nav-item nav-link" href="{{url_for('users.myapostas') }}">As minhas Apostas</a>
                <a class="nav-item nav-link" href="{{url_for('apostas.novaAposta') }}">Nova Aposta</a>
                <a class="nav-item nav-link" href="{{url_for('users.conta') }}">A minha conta</a>
                <a class="nav-item nav-link" href="{{url_for('users.logout') }}">Logout</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {%if messages%}
                    {% for category, message in messages %}
                        <div class="alert alert-{{category}}">
                            {{message}}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
          {% block content %}{% endblock %}
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

projeto/templates/login.html
{% extends "layout.html" %}

{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{form.hidden_tag()}}
            <fieldset class="form-group">
                <legend class=border-bottom mb-4">Login</legend>
                <div class="form-group">
                    {{form.email.label(class="form-control-label")}}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{form.password.label(class="form-control-label")}}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{form.remember(class="form-check-input")}}
                    {{form.remember.label(class="form-ckeck-label")}}
                </div>
                </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
            <small class="text-muted ml-2">
                <a href="#">Esqueceu-se da password?</a>
            </small>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class ="text-muted">
            Não tem uma conta? <a class="ml-2" href="{{ url_for('users.registo')}}"> Registe-se </a>
        </small>
    </div>
{% endblock %}

projeto/templates/quest.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <div class="form-group">
                {{ form.content.label(class="form-control-label") }}
                {% if form.content.errors %}
                    {{ form.content(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.content.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.content(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content %}